// <auto-generated />
using System;
using AtlasFoxAPI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AtlasFoxAPI.Migrations
{
    [DbContext(typeof(_DbContext))]
    [Migration("20231207042431_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AtlasFoxAPI.Model.FormDetail", b =>
                {
                    b.Property<string>("rowid")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("rowid");

                    b.Property<string>("form_id")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("form_id");

                    b.Property<int?>("jumlah")
                        .HasColumnType("int")
                        .HasColumnName("jumlah");

                    b.Property<string>("satuan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("satuan");

                    b.Property<string>("spesifikasi")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("spesifikasi");

                    b.Property<string>("uraian")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("uraian");

                    b.HasKey("rowid");

                    b.ToTable("FormDetail");
                });

            modelBuilder.Entity("AtlasFoxAPI.Model.FormPPK", b =>
                {
                    b.Property<string>("form_id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("form_id");

                    b.Property<string>("departement_karyawan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("departement_karyawan");

                    b.Property<string>("detail_jenis_kebutuhan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("detail_jenis_kebutuhan");

                    b.Property<string>("jabatan_karyawan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("jabatan_karyawan");

                    b.Property<int?>("jenis_kebutuhan")
                        .HasColumnType("int")
                        .HasColumnName("jenis_kebutuhan");

                    b.Property<string>("nama_karyawan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_karyawan");

                    b.Property<string>("nama_kebutuhan")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nama_kebutuhan");

                    b.Property<string>("nik_manager")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nik_manager");

                    b.Property<DateTime?>("tanggal_pembelian")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_pembelian");

                    b.Property<DateTime?>("tanggal_permintaan")
                        .HasColumnType("datetime2")
                        .HasColumnName("tanggal_permintaan");

                    b.Property<string>("user_id")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("user_id");

                    b.HasKey("form_id");

                    b.ToTable("FormPPK");
                });
#pragma warning restore 612, 618
        }
    }
}
